export type TOrder = {
  file_id: string;
  data: TOrderData;
};
export type TOrderData = {
  BUYER_EMAIL: string;
  BUYER_NAME: string;
  CHANNEL: string;
  CHANNEL_NAME: string;
  CURRENCY_CODE: string;
  EAN: any;
  ITEM_PRICE: number;
  ITEM_TAX: number;
  ORDER_DATE: number;
  ORDER_ID: string;
  ORDER_ITEM_ID: number;
  ORDER_STATUS: string;
  ORDER_TOTAL: number;
  PAYMENT_STATUS: string;
  QUANTITY_PURCHASED: number;
  SELRO_ORDER_ID: number;
  SHIPPING_CARRIER: string;
  SHIPPING_COST: number;
  SHIPPING_METHOD: string;
  SHIP_ADDRESS_1: string;
  SHIP_ADDRESS_2: string;
  SHIP_CITY: string;
  SHIP_COUNTRY: string;
  SHIP_COUNTRY_CODE: string;
  SHIP_POSTALCODE: string;
  SHIP_STATE: string;
  SITE: string;
  SKU: string;
  SUB_TOTAL: number;
  TITLE: string;
  TOTAL_PRICE: number;
  UPC: number;
  WEIGHT_KG: number;
};
